### ISSUE TITLE
Unable to resolve Action

### ISSUE THREAD

**Issue by cjbischoff** [niravpatel27/gh-action-spdx-sbom-generator#1]
Thank you for putting together this GitHub Action.

Apparently, it cannot access/resolve the GitHub Action per the error

```
Failed to resolve action download info. Error: Unable to resolve action `niravpatel27/gh-action-spdx-sbom-generator@v1`, unable to find version `v1`
Retrying in 26.028 seconds
Failed to resolve action download info. Error: Unable to resolve action `niravpatel27/gh-action-spdx-sbom-generator@v1`, unable to find version `v1`
Retrying in 21.282 seconds
Error: Unable to resolve action `niravpatel27/gh-action-spdx-sbom-generator@v1`, unable to find version `v1`
```

This is how I was invoking the action

```
  spdx-sbom:
    name: SPDX/spdx-sbom
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Generate SBOM(spdx-sbom)
        uses: niravpatel27/gh-action-spdx-sbom-generator@v1
        with:
          version: '0.0.3'
```

**Comment by niravpatel27** [comment]
@cjbischoff thanks for checking it out.

please use like ` uses: niravpatel27/gh-action-spdx-sbom-generator@v1.0.0` instead of ` uses: niravpatel27/gh-action-spdx-sbom-generator@v1` that should resolve the issue.

Here is a working example: https://github.com/spdx/spdx-sbom-generator/blob/main/.github/workflows/build.yml#L31 that I am using on the spdx gen tool.

**Comment by niravpatel27** [comment]
I have also corrected the readme example.
